import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "../../public/fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../../public/fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const geistArial = localFont({
  src: "../../public/fonts/arial/ARIAL.woff",
  variable: "--font-arial",
  weight: "100 900",
})

export const metadata: Metadata = {
  title: "NusaGO",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${geistArial.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
